import React, { useState, useEffect } from "react";
import type { Recipe } from "../api/gemini";
import { Clock, Users, Copy, Check, CheckSquare, Square } from "lucide-react";
import { fetchRecipeVideo } from "../api/youtube";

interface RecipeCardProps {
  recipe: Recipe;
  peopleCount: number;
}

export const RecipeCard: React.FC<RecipeCardProps> = ({ recipe, peopleCount }) => {
  const [copied, setCopied] = useState(false);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [boughtIngredients, setBoughtIngredients] = useState<string[]>([]);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [videoLoading, setVideoLoading] = useState(false);

  useEffect(() => {
    let isMounted = true;
    const loadVideo = async () => {
      setVideoLoading(true);
      const url = await fetchRecipeVideo(recipe.name);
      if (isMounted) {
        setVideoUrl(url);
        setVideoLoading(false);
      }
    };
    loadVideo();
    return () => {
      isMounted = false;
    };
  }, [recipe.name]);

  const toggleStep = (index: number) => {
    if (completedSteps.includes(index)) {
      setCompletedSteps(completedSteps.filter(i => i !== index));
    } else {
      setCompletedSteps([...completedSteps, index]);
    }
  };

  const toggleIngredient = (name: string) => {
    if (boughtIngredients.includes(name)) {
      setBoughtIngredients(boughtIngredients.filter(n => n !== name));
    } else {
      setBoughtIngredients([...boughtIngredients, name]);
    }
  };

  const handleShare = () => {
    const textSummary = `🍳 ${recipe.name}\n${recipe.description}\n\n💰 Total Cost to Cook: ₱${recipe.totalCost} (₱${recipe.costPerPerson}/person for ${peopleCount} pax)\n⏱️ Time: ${recipe.prepTime} mins\n\n🛒 Ingredients:\n${recipe.ingredients.map(ing => `- [${ing.isOwned ? "x" : " "}] ${ing.amount} ${ing.name} (${ing.isOwned ? "Owned" : `₱${ing.estimatedCost}`})`).join("\n")}\n\n📋 Cooking Steps:\n${recipe.steps.map((step, idx) => `${idx + 1}. ${step}`).join("\n")}\n\nGenerated by UlamGPT 🇵🇭`;

    navigator.clipboard.writeText(textSummary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <article className="card recipe-card">
      <div className="recipe-header">
        <div>
          <h3 className="recipe-title">{recipe.name}</h3>
          <p style={{ fontSize: "0.85rem", marginTop: "0.25rem" }}>{recipe.description}</p>
        </div>
        <div className="recipe-cost-badge">
          ₱{recipe.totalCost}
        </div>
      </div>

      <div className="recipe-meta">
        <div className="recipe-meta-item">
          <Clock size={16} />
          <span>{recipe.prepTime} mins</span>
        </div>
        <div className="recipe-meta-item">
          <Users size={16} />
          <span>{recipe.costPerPerson ? `₱${recipe.costPerPerson}/person` : ""} ({peopleCount} pax)</span>
        </div>
      </div>

      <div style={{ marginBottom: "1.25rem" }}>
        <h4 className="recipe-section-title">Ingredients Checklist</h4>
        <ul className="ingredients-list">
          {recipe.ingredients.map((ing, idx) => {
            const hasChecked = ing.isOwned || boughtIngredients.includes(ing.name);
            return (
              <li 
                key={idx} 
                className={`ingredient-item ${hasChecked ? "owned" : ""}`}
                style={{ cursor: "pointer" }}
                onClick={() => toggleIngredient(ing.name)}
              >
                <span style={{ color: hasChecked ? "var(--color-accent-green)" : "var(--color-primary-terracotta)" }}>
                  {hasChecked ? <CheckSquare size={16} /> : <Square size={16} />}
                </span>
                <span>
                  <strong>{ing.amount}</strong> {ing.name}{" "}
                  {!ing.isOwned && <span style={{ fontSize: "0.75rem", opacity: 0.8 }}>(~₱{ing.estimatedCost})</span>}
                  {ing.isOwned && <span style={{ fontSize: "0.75rem", color: "var(--color-accent-green)" }}> (pantry)</span>}
                </span>
              </li>
            );
          })}
        </ul>
      </div>

      <div style={{ marginBottom: "1.5rem" }}>
        <h4 className="recipe-section-title">Interactive Cooking Steps</h4>
        <ol className="steps-list">
          {recipe.steps.map((step, idx) => {
            const isCompleted = completedSteps.includes(idx);
            return (
              <li 
                key={idx} 
                className="step-item"
                style={{ 
                  cursor: "pointer", 
                  textDecoration: isCompleted ? "line-through" : "none", 
                  opacity: isCompleted ? 0.5 : 1,
                  transition: "all var(--transition-fast) ease"
                }}
                onClick={() => toggleStep(idx)}
              >
                {step}
              </li>
            );
          })}
        </ol>
      </div>

      {/* Embedded YouTube Tutorial Video */}
      <div style={{ marginBottom: "1.5rem" }}>
        <h4 className="recipe-section-title">📺 Video Tutorial</h4>
        {videoLoading ? (
          <div style={{ 
            height: "180px", 
            background: "rgba(194, 65, 12, 0.03)", 
            borderRadius: "var(--radius-md)", 
            display: "flex", 
            alignItems: "center", 
            justifyContent: "center", 
            border: "1px dashed var(--color-border)",
            color: "var(--color-text-light)",
            fontSize: "0.85rem"
          }}>
            Searching YouTube tutorial...
          </div>
        ) : videoUrl ? (
          <div style={{ 
            position: "relative", 
            width: "100%", 
            paddingBottom: "56.25%", /* 16:9 Aspect Ratio */
            height: 0, 
            borderRadius: "var(--radius-md)", 
            overflow: "hidden", 
            boxShadow: "var(--shadow-sm)", 
            border: "1px solid var(--color-border)"
          }}>
            <iframe
              src={videoUrl}
              title={`${recipe.name} Tutorial`}
              style={{ 
                position: "absolute", 
                top: 0, 
                left: 0, 
                width: "100%", 
                height: "100%", 
                border: 0 
              }}
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
            />
          </div>
        ) : (
          <div style={{ 
            padding: "1rem", 
            background: "var(--color-bg-cream)", 
            borderRadius: "var(--radius-md)", 
            textAlign: "center", 
            fontSize: "0.85rem", 
            color: "var(--color-text-light)" 
          }}>
            No video tutorial found.
          </div>
        )}
      </div>

      <div style={{ display: "flex", gap: "1rem", marginTop: "auto", borderTop: "1px solid var(--color-border)", paddingTop: "1rem", marginBottom: "1rem" }}>
        <button className="btn btn-secondary" style={{ flex: 1 }} onClick={handleShare}>
          {copied ? <Check size={16} /> : <Copy size={16} />}
          <span>{copied ? "Copied!" : "Share Recipe"}</span>
        </button>
      </div>

      <div className="nutrition-grid">
        <div className="nutrition-item">
          <div className="nutrition-value">{recipe.nutrition.calories}</div>
          <div className="nutrition-label">kcal</div>
        </div>
        <div className="nutrition-item">
          <div className="nutrition-value">{recipe.nutrition.protein}</div>
          <div className="nutrition-label">Protein</div>
        </div>
        <div className="nutrition-item">
          <div className="nutrition-value">{recipe.nutrition.carbs}</div>
          <div className="nutrition-label">Carbs</div>
        </div>
        <div className="nutrition-item">
          <div className="nutrition-value">{recipe.nutrition.fat}</div>
          <div className="nutrition-label">Fat</div>
        </div>
      </div>
    </article>
  );
};
